const BAD_REQUEST = 400;
const NOT_FOUND = 404;
const DEFAULT_ERROR = 500;
const AUTHORIZATION_ERROR = 401;
const FORBIDDEN = 403;
const CONFLICT = 409;

module.exports = {
  BAD_REQUEST,
  NOT_FOUND,
  DEFAULT_ERROR,
  AUTHORIZATION_ERROR,
  FORBIDDEN,
  CONFLICT,
};
